// Initial static data for live ranking simulator.
// Teams 1-4: all alive. Teams 5-6: 3 alive, 1 knocked. Teams 7-8: 2 alive, 2 dead. Teams 9+: all eliminated.
export const initialData = [
  {
    rank: 1,
    team: {
      _id: "69dfc96b8811ec6c51d5fbdb",
      name: "Team 4",
      index: 4,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 100,
        ign: "RGgCelestine٭",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 95,
        ign: "RGgMiKaMikiee",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 88,
        ign: "RGgAnnGieeeɞ",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 72,
        ign: "RGgAYRA",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
    ],
    points: 18,
    overAllPoints: 18,
    kills: 18,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 2,
    team: {
      _id: "69dfc9718811ec6c51d5fbdc",
      name: "team 5",
      index: 5,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      // { healths: 100, ign: "S2KxGABIMARUz", isAlive: true, liveState: 0, isOutsideZone: false },
      // { healths: 80,  ign: "EFesPsyDuck",   isAlive: true, liveState: 0, isOutsideZone: false },
      // { healths: 65,  ign: "WOWerBAP",       isAlive: true, liveState: 0, isOutsideZone: false },
      // { healths: 90,  ign: "EFesWiZzBoYy",  isAlive: true, liveState: 0, isOutsideZone: false },
    ],
    points: 15,
    overAllPoints: 15,
    kills: 15,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 3,
    team: {
      _id: "69dfc9788811ec6c51d5fbdd",
      name: "Team 6",
      index: 6,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 85,
        ign: "NMxBSTvAmP",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 100,
        ign: "ZORxAluuuuU",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 55,
        ign: "NMxBSTcYcLoNe",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 70,
        ign: "NMxBSTpHaNtOm",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
    ],
    points: 12,
    overAllPoints: 12,
    kills: 12,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 4,
    team: {
      _id: "69dfc97e8811ec6c51d5fbde",
      name: "team 7",
      index: 7,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 92,
        ign: "waveSTR3TCHx",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 78,
        ign: "SPYROzz",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 60,
        ign: "JGxBLAZEi",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 45,
        ign: "YUTA・OKKuTSU",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
    ],
    points: 10,
    overAllPoints: 10,
    kills: 10,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 5,
    team: {
      _id: "69dfc9868811ec6c51d5fbdf",
      name: "team 8",
      index: 8,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 75,
        ign: "TGesPAPAŵ",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 50,
        ign: "TGesViruS",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 30,
        ign: "TGesButcherOG",
        isAlive: true,
        liveState: 4,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "TGesSUPREME",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 8,
    overAllPoints: 8,
    kills: 8,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 6,
    team: {
      _id: "69dfc98c8811ec6c51d5fbe0",
      name: "team 9",
      index: 9,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 60,
        ign: "NFxWONDERBOY",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 40,
        ign: "i4SxINcompleTe",
        isAlive: true,
        liveState: 4,
        isOutsideZone: false,
      },
      {
        healths: 55,
        ign: "ROYLxWILDBOY",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "SFesCRushER",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 8,
    overAllPoints: 8,
    kills: 8,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 7,
    team: {
      _id: "69dfc9948811ec6c51d5fbe1",
      name: "team 10",
      index: 10,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 45,
        ign: "TReZz",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 20,
        ign: "WTesNEYOー11",
        isAlive: true,
        liveState: 4,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "WTesAKAZAoP",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "WTesTHORNoP",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 7,
    overAllPoints: 7,
    kills: 7,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 8,
    team: {
      _id: "69dfc99a8811ec6c51d5fbe2",
      name: "team 11",
      index: 11,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 35,
        ign: "T7esShadoW",
        isAlive: true,
        liveState: 0,
        isOutsideZone: false,
      },
      {
        healths: 15,
        ign: "4EmpSH4NKS",
        isAlive: true,
        liveState: 4,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "4EmpH3LCuRT",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "4EmpD4RKegiL",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 6,
    overAllPoints: 6,
    kills: 6,
    isMissing: false,
    winProbability: null,
  },
  // --- All teams below are already eliminated ---
  {
    rank: 9,
    team: {
      _id: "69dfc9a08811ec6c51d5fbe3",
      name: "team 12",
      index: 12,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "KriegerV4X",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "H1N0K4MiV4X",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "PhAnToMzV4X",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "ConsumptionV4X",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 5,
    overAllPoints: 5,
    kills: 5,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 10,
    team: {
      _id: "69dfc9a88811ec6c51d5fbe4",
      name: "team 13",
      index: 13,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "AQBesPrimeOp",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "ZG71esYoriichi",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "AQBesK1ngPin",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "X4esMACHINE",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 4,
    overAllPoints: 4,
    kills: 4,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 11,
    team: {
      _id: "69dfc9af8811ec6c51d5fbe5",
      name: "team 14",
      index: 14,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "FEesMANGO",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "FEesUniQuE",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "FEesNEXTA",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "FEesSOLOMAN",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 4,
    overAllPoints: 4,
    kills: 4,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 12,
    team: {
      _id: "69dfc9b58811ec6c51d5fbe6",
      name: "team 15",
      index: 15,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "SAesLockBaee",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "IUBATxNeutrino",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "BDxNONCHALANT1",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "SAesSPIDYoP",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 3,
    overAllPoints: 3,
    kills: 3,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 13,
    team: {
      _id: "69dfc9bf8811ec6c51d5fbe7",
      name: "team 16",
      index: 16,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "DgXesRavaL",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "DgXesHYPER",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "DgXesFexo",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "DgXesFraGGer",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 3,
    overAllPoints: 3,
    kills: 3,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 14,
    team: {
      _id: "69dfc9c88811ec6c51d5fbe8",
      name: "team 17",
      index: 17,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "WwQUiCKzZz",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "POHesMrOggy",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "7DesTiGER",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "DADDYŪAyan",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 2,
    overAllPoints: 2,
    kills: 2,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 15,
    team: {
      _id: "69dfc9d88811ec6c51d5fbe9",
      name: "team 18",
      index: 18,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "7SinsHalalBoi",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "iW死神",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "iWxDOK",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "7SinsZORO47",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 2,
    overAllPoints: 2,
    kills: 2,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 16,
    team: {
      _id: "69dfc9e48811ec6c51d5fbea",
      name: "team 19",
      index: 19,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "3sixT×Apex",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "3sixTャKRIEGER",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "APxHUNT",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "MohawkYTLive",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 1,
    overAllPoints: 1,
    kills: 1,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 17,
    team: {
      _id: "69dfc9ed8811ec6c51d5fbeb",
      name: "team 20",
      index: 20,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "SRESTHAfromTS",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "PANDAfromTS",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "MAKOBOYfromTS",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "SAYMAfromTS",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 1,
    overAllPoints: 1,
    kills: 1,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 18,
    team: {
      _id: "69dfc9f58811ec6c51d5fbec",
      name: "team 21",
      index: 21,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "ÎMTesＰＩＸＵ",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "ÎMTesLIZARD",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "JGxKiLLeRRR",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "JGxLeoX16Zzz",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 1,
    overAllPoints: 1,
    kills: 1,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 19,
    team: {
      _id: "69dfc9fb8811ec6c51d5fbed",
      name: "team 22",
      index: 22,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "CAPTesMEHEDIII",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "CAPTesZoDXOP",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "๛ZUES๛",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "CAPTesAthenaYT",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 1,
    overAllPoints: 1,
    kills: 1,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 20,
    team: {
      _id: "69dfca028811ec6c51d5fbee",
      name: "team 23",
      index: 23,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "V7rHEXAGON",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "TMesPUTUuxTiG",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "TMesEDEV1LxTiG",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "TMesSLASHYxTiG",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 1,
    overAllPoints: 1,
    kills: 1,
    isMissing: false,
    winProbability: null,
  },
  {
    rank: 21,
    team: {
      _id: "69dfca0f8811ec6c51d5fbef",
      name: "team 24",
      index: 24,
      logoImageUrl:
        "https://api.esportsawardsbd.com/images/defaults/default-team.png",
    },
    players: [
      {
        healths: 0,
        ign: "GFOXesBen10",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "GFOXesMuS",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "GFOXesSAKIBsir",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
      {
        healths: 0,
        ign: "G66xZUXXY",
        isAlive: false,
        liveState: 5,
        isOutsideZone: false,
      },
    ],
    points: 0,
    overAllPoints: 0,
    kills: 0,
    isMissing: false,
    winProbability: null,
  },
];
